config/routes.rb
Rails.application.routes.draw do
  resources :tbms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tbm.rb
class Tbm < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tbms_controller.rb
class TbmsController < ApplicationController
  before_action :set_tbm, only: [:show, :edit, :update, :destroy]

  # GET /tbms
  # GET /tbms.json
  def index
    @tbms = Tbm.all
  end

  # GET /tbms/1
  # GET /tbms/1.json
  def show
  end

  # GET /tbms/new
  def new
    @tbm = Tbm.new
  end

  # GET /tbms/1/edit
  def edit
  end

  # POST /tbms
  # POST /tbms.json
  def create
    @tbm = Tbm.new(tbm_params)

    respond_to do |format|
      if @tbm.save
        format.html { redirect_to @tbm, notice: 'Tbm was successfully created.' }
        format.json { render :show, status: :created, location: @tbm }
      else
        format.html { render :new }
        format.json { render json: @tbm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tbms/1
  # PATCH/PUT /tbms/1.json
  def update
    respond_to do |format|
      if @tbm.update(tbm_params)
        format.html { redirect_to @tbm, notice: 'Tbm was successfully updated.' }
        format.json { render :show, status: :ok, location: @tbm }
      else
        format.html { render :edit }
        format.json { render json: @tbm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tbms/1
  # DELETE /tbms/1.json
  def destroy
    @tbm.destroy
    respond_to do |format|
      format.html { redirect_to tbms_url, notice: 'Tbm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tbm
      @tbm = Tbm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tbm_params
      params.require(:tbm).permit(:name, :add, :kin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tbms_helper.rb
module TbmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rvtst27</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tbms/_form.html.erb
<%= form_with(model: tbm, local: true) do |form| %>
  <% if tbm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tbm.errors.count, "error") %> prohibited this tbm from being saved:</h2>

      <ul>
        <% tbm.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :add %>
    <%= form.text_field :add %>
  </div>

  <div class="field">
    <%= form.label :kin %>
    <%= form.number_field :kin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tbms/edit.html.erb
<h1>Editing Tbm</h1>

<%= render 'form', tbm: @tbm %>

<%= link_to 'Show', @tbm %> |
<%= link_to 'Back', tbms_path %>

app/views/tbms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tbms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Add</th>
      <th>Kin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tbms.each do |tbm| %>
      <tr>
        <td><%= tbm.name %></td>
        <td><%= tbm.add %></td>
        <td><%= tbm.kin %></td>
        <td><%= link_to 'Show', tbm %></td>
        <td><%= link_to 'Edit', edit_tbm_path(tbm) %></td>
        <td><%= link_to 'Destroy', tbm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tbm', new_tbm_path %>

app/views/tbms/new.html.erb
<h1>New Tbm</h1>

<%= render 'form', tbm: @tbm %>

<%= link_to 'Back', tbms_path %>

app/views/tbms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tbm.name %>
</p>

<p>
  <strong>Add:</strong>
  <%= @tbm.add %>
</p>

<p>
  <strong>Kin:</strong>
  <%= @tbm.kin %>
</p>

<%= link_to 'Edit', edit_tbm_path(@tbm) %> |
<%= link_to 'Back', tbms_path %>